### ISSUE TITLE
Library request on CDNJS

### ISSUE THREAD

**Issue by extend1994** [yusugomori/csssans#7]
Hi
I am a member of CDNJS and also the one in charge of adding your library to CDNJS according to the request cdnjs/cdnjs#10510. On CDNJS, we get the required file automatically by a mechanism called auto-update which needs the tag/release. Or we have to add the files manually. It's less effective for us and your users. Is it possible for you to use a tag/release? 
For more details about tag and release, here are the references: 
https://git-scm.com/book/en/v2/Git-Basics-Tagging
https://help.github.com/articles/creating-releases/

Thank you!

**Comment by yusugomori** [comment]
@extend1994 
Thank you for your message. I've added the tag https://github.com/yusugomori/csssans/releases .
Could you check it?

Thanks

**Comment by extend1994** [comment]
Thanks @yusugomori 
It should work now 💪 
There is another question: Is it possible for you to change the naming scheme for the files? We need a filename without involving a version number for our auto-update mechanism.
> Filenames should not include a version number and be lowercase.
This is OK: useful.min.js, but this is not: useful-2.0.1.min.js.

Ref: https://github.com/cdnjs/cdnjs/blob/master/CONTRIBUTING.md#b-common-conventions

**Comment by yusugomori** [comment]
Hi @extend1994

I've just updated file names, and re-tagged the current codes as `v1.0.0` 👍

**Comment by extend1994** [comment]
@yusugomori Thank you so much! I will notify you once I create a pull request in CDNJS to add your library 😄
